instance: 0
batch_size: 128
epochs: 150
num_workers: 8
remove_checkpoints: False
adam:
  lr: 0.00001
  betas: [0.9, 0.999]
  eps: 1e-8
  weight_decay: 0.001
compute_accuracy: False
tensorboard: True
checkpoint_interval: 10
step_lr:
  gamma: 0.1
  step_size: 290
